name: Cloud-Gateway

on:
  push:
    branches: [ "main" ]
    paths: 
    - 'cloud-gateway/**'
  workflow_run:
    workflows:
      - "Service Registry"
    types:
      - completed

jobs:
  deploying:
    if: ${{ github.event_name == 'workflow_run' }}
    uses: ./.github/workflows/common_job.yml
    with:
      JAR_FILE_NAME: 'cloud-gateway-0.0.1-SNAPSHOT.jar'
      TARGET_PATH: 'cloud-gateway'
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}'
    
  deploying2:
    if: ${{ github.event_name == 'push' && !contains(github.event.workflow_run.workflow, 'Cloud-Gateway') }}
    uses: ./.github/workflows/common_job.yml
    with:
      JAR_FILE_NAME: 'cloud-gateway-0.0.1-SNAPSHOT.jar'
      TARGET_PATH: 'cloud-gateway'
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}'
