name: Service Registry

on:
  push:
    branches:
      - main
    paths: 
     - 'service_registry/**'

jobs:
  deploying:
    uses: ./.github/workflows/common_job.yml
    with:
      JAR_FILE_NAME: 'service_registry-0.0.1-SNAPSHOT.jar'
      TARGET_PATH: 'service_registry'
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
