name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths: 
     - 'service_registry/**'

env:
  JAR_FILE_NAME: 'service_registry-0.0.1-SNAPSHOT.jar'
  TARGET_PATH: 'service_registry'
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  Test:
    uses: ./.github/workflows/common_job.yml
    with:
      JAR_FILE_NAME: 'service_registry-0.0.1-SNAPSHOT.jar'
      TARGET_PATH: 'service_registry'
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
